#include "Units/Berserker.h"
#include "Units/Soldier.h"
#include "Units/Rogue.h"
#include "Units/Vampire.h"
#include "Units/Werewolf.h"

#include "States/Attack.h"
#include "States/HumanState.h"
#include "States/WolfState.h"
#include "States/VampireState.h"